project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-VZ2D2CGVTS"
    anonymize-ip: true
format:
  html:
    theme: cosmo
    css: styles.css
